# Base configs
baseurl: "https://aalok-sathe.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
#google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Aalok Sathe"
subtitle: "coming soon"
author: "Aalok Sathe"
header:
 title: "Photography"
 subtitle: "by Aalok Sathe"
footer:
 name: "Hey there, my name is Aalok"
 bio: "I am a student interested math, CS, linguistics, philosophy, the brain, and complex systems (in no particular order). I am a FOSS enthusiast."
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
  twitter: "https://www.twitter.com/aalok_sathe"
  instagram: "https://www.instagram.com/aalok__"
  github: "https://www.github.com/aalok-sathe"
